import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { CookiesProvider } from 'next-client-cookies/server';
import QueryProvider from '@/provider/QueryProvider';
import { CartProvider } from '@/provider/CartProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CookiesProvider>
          <QueryProvider>
            <CartProvider>{children}</CartProvider>
          </QueryProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
